apiVersion: apps/v1
kind: Deployment
metadata:
  name: reindeer-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: reindeer-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reindeer-app
    spec:
      containers:
        - image: gcr.io/gks-sample/reindeer-service-image:v1
          imagePullPolicy: IfNotPresent # looks for image locally, then at configured public registries
          name: reindeer-service-container
          ports:
            - containerPort: 8080
